src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReclamationRepository::class)
 */
class Reclamation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_recla;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Contenu_recla;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="UserOneReclamation")
     */
    private $manyUser;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reclamations")
     */
    private $manyReclamationUser;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateRecla(): ?\DateTimeInterface
    {
        return $this->date_recla;
    }

    public function setDateRecla(\DateTimeInterface $date_recla): self
    {
        $this->date_recla = $date_recla;

        return $this;
    }

    public function getContenuRecla(): ?string
    {
        return $this->Contenu_recla;
    }

    public function setContenuRecla(string $Contenu_recla): self
    {
        $this->Contenu_recla = $Contenu_recla;

        return $this;
    }

    public function getManyUser(): ?User
    {
        return $this->manyUser;
    }

    public function setManyUser(?User $manyUser): self
    {
        $this->manyUser = $manyUser;

        return $this;
    }

    public function getManyReclamationUser(): ?User
    {
        return $this->manyReclamationUser;
    }

    public function setManyReclamationUser(?User $manyReclamationUser): self
    {
        $this->manyReclamationUser = $manyReclamationUser;

        return $this;
    }


}

src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_recla')
            ->add('Contenu_recla')
            ->add('manyUser')
            ->add('manyReclamationUser')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;

use App\Entity\Reclamation;
use App\Form\ReclamationType;
use App\Repository\ReclamationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/reclamation")
 */
class ReclamationController extends AbstractController
{
    /**
     * @Route("/", name="reclamation_index", methods={"GET"})
     */
    public function index(ReclamationRepository $reclamationRepository): Response
    {
        return $this->render('reclamation/index.html.twig', [
            'reclamations' => $reclamationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="reclamation_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $reclamation = new Reclamation();
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reclamation);
            $entityManager->flush();

            return $this->redirectToRoute('reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reclamation/new.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="reclamation_show", methods={"GET"})
     */
    public function show(Reclamation $reclamation): Response
    {
        return $this->render('reclamation/show.html.twig', [
            'reclamation' => $reclamation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reclamation_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Reclamation $reclamation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reclamation/edit.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="reclamation_delete", methods={"POST"})
     */
    public function delete(Request $request, Reclamation $reclamation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reclamation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($reclamation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reclamation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reclamation/_delete_form.html.twig
<form method="post" action="{{ path('reclamation_delete', {'id': reclamation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reclamation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reclamation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reclamation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reclamation{% endblock %}

{% block body %}
    <h1>Edit Reclamation</h1>

    {{ include('reclamation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('reclamation_index') }}">back to list</a>

    {{ include('reclamation/_delete_form.html.twig') }}
{% endblock %}

templates/reclamation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reclamation index{% endblock %}

{% block body %}
    <h1>Reclamation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_recla</th>
                <th>Contenu_recla</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reclamation in reclamations %}
            <tr>
                <td>{{ reclamation.id }}</td>
                <td>{{ reclamation.dateRecla ? reclamation.dateRecla|date('Y-m-d') : '' }}</td>
                <td>{{ reclamation.ContenuRecla }}</td>
                <td>
                    <a href="{{ path('reclamation_show', {'id': reclamation.id}) }}">show</a>
                    <a href="{{ path('reclamation_edit', {'id': reclamation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('reclamation_new') }}">Create new</a>
{% endblock %}

templates/reclamation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reclamation{% endblock %}

{% block body %}
    <h1>Create new Reclamation</h1>

    {{ include('reclamation/_form.html.twig') }}

    <a href="{{ path('reclamation_index') }}">back to list</a>
{% endblock %}

templates/reclamation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reclamation{% endblock %}

{% block body %}
    <h1>Reclamation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reclamation.id }}</td>
            </tr>
            <tr>
                <th>Date_recla</th>
                <td>{{ reclamation.dateRecla ? reclamation.dateRecla|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Contenu_recla</th>
                <td>{{ reclamation.ContenuRecla }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('reclamation_index') }}">back to list</a>

    <a href="{{ path('reclamation_edit', {'id': reclamation.id}) }}">edit</a>

    {{ include('reclamation/_delete_form.html.twig') }}
{% endblock %}