src/Entity/Inscription.php
<?php

namespace App\Entity;

use App\Repository\InscriptionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InscriptionRepository::class)
 */
class Inscription
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $Date_formation;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_condidat;
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="inscriptions")
     */
    private $InscritUser;


    /**
     * @ORM\ManyToOne(targetEntity=Formation::class, inversedBy="FormaInscrit")
     */
    private $formation;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateFormation(): ?\DateTimeInterface
    {
        return $this->Date_formation;
    }

    public function setDateFormation(\DateTimeInterface $Date_formation): self
    {
        $this->Date_formation = $Date_formation;

        return $this;
    }

    public function getNombreCondidat(): ?int
    {
        return $this->nombre_condidat;
    }

    public function setNombreCondidat(int $nombre_condidat): self
    {
        $this->nombre_condidat = $nombre_condidat;

        return $this;
    }

    public function getInscritUser(): ?User
    {
        return $this->InscritUser;
    }

    public function setInscritUser(?User $InscritUser): self
    {
        $this->InscritUser = $InscritUser;

        return $this;
    }



    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): self
    {
        $this->formation = $formation;

        return $this;
    }


}

src/Form/InscriptionType.php
<?php

namespace App\Form;

use App\Entity\Inscription;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InscriptionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Date_formation')
            ->add('nombre_condidat')
            ->add('InscritUser')
            ->add('formation')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Inscription::class,
        ]);
    }
}

src/Controller/InscriptionController.php
<?php

namespace App\Controller;

use App\Entity\Inscription;
use App\Form\InscriptionType;
use App\Repository\InscriptionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/inscription")
 */
class InscriptionController extends AbstractController
{
    /**
     * @Route("/", name="inscription_index", methods={"GET"})
     */
    public function index(InscriptionRepository $inscriptionRepository): Response
    {
        return $this->render('inscription/index.html.twig', [
            'inscriptions' => $inscriptionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="inscription_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $inscription = new Inscription();
        $form = $this->createForm(InscriptionType::class, $inscription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($inscription);
            $entityManager->flush();

            return $this->redirectToRoute('inscription_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('inscription/new.html.twig', [
            'inscription' => $inscription,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="inscription_show", methods={"GET"})
     */
    public function show(Inscription $inscription): Response
    {
        return $this->render('inscription/show.html.twig', [
            'inscription' => $inscription,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="inscription_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Inscription $inscription, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(InscriptionType::class, $inscription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('inscription_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('inscription/edit.html.twig', [
            'inscription' => $inscription,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="inscription_delete", methods={"POST"})
     */
    public function delete(Request $request, Inscription $inscription, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$inscription->getId(), $request->request->get('_token'))) {
            $entityManager->remove($inscription);
            $entityManager->flush();
        }

        return $this->redirectToRoute('inscription_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/inscription/_delete_form.html.twig
<form method="post" action="{{ path('inscription_delete', {'id': inscription.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ inscription.id) }}">
    <button class="btn">Delete</button>
</form>

templates/inscription/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/inscription/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Inscription{% endblock %}

{% block body %}
    <h1>Edit Inscription</h1>

    {{ include('inscription/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('inscription_index') }}">back to list</a>

    {{ include('inscription/_delete_form.html.twig') }}
{% endblock %}

templates/inscription/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription index{% endblock %}

{% block body %}
    <h1>Inscription index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_formation</th>
                <th>Nombre_condidat</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for inscription in inscriptions %}
            <tr>
                <td>{{ inscription.id }}</td>
                <td>{{ inscription.DateFormation ? inscription.DateFormation|date('Y-m-d') : '' }}</td>
                <td>{{ inscription.nombreCondidat }}</td>
                <td>
                    <a href="{{ path('inscription_show', {'id': inscription.id}) }}">show</a>
                    <a href="{{ path('inscription_edit', {'id': inscription.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('inscription_new') }}">Create new</a>
{% endblock %}

templates/inscription/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Inscription{% endblock %}

{% block body %}
    <h1>Create new Inscription</h1>

    {{ include('inscription/_form.html.twig') }}

    <a href="{{ path('inscription_index') }}">back to list</a>
{% endblock %}

templates/inscription/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription{% endblock %}

{% block body %}
    <h1>Inscription</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ inscription.id }}</td>
            </tr>
            <tr>
                <th>Date_formation</th>
                <td>{{ inscription.DateFormation ? inscription.DateFormation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nombre_condidat</th>
                <td>{{ inscription.nombreCondidat }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('inscription_index') }}">back to list</a>

    <a href="{{ path('inscription_edit', {'id': inscription.id}) }}">edit</a>

    {{ include('inscription/_delete_form.html.twig') }}
{% endblock %}